services:
  - type: web
    name: summarai-text-summarizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
